export enum NfcError {
  NOT_SUPPORTED = 'NOT_SUPPORTED',
  PERMISSION_DENIED = 'PERMISSION_DENIED',
  INVALID_TARGET = 'INVALID_TARGET',
  TIMEOUT = 'TIMEOUT',
  ABORT = 'ABORT',
  SYNTAX_ERROR = 'SYNTAX_ERROR',
  NETWORK_ERROR = 'NETWORK_ERROR',
  NO_DATA = 'NO_DATA',
  READER_NOT_STARTED = 'READER_NOT_STARTED',
  UNSUPPORTED_OPERATION = 'UNSUPPORTED_OPERATION',
  UNSUPPORTED_RECORD_TYPE = 'UNSUPPORTED_RECORD_TYPE',
}
